services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app-srm-gestao
    container_name: laravel-app-srm-gestao
    working_dir: /var/www
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www
      - vendor:/var/www/vendor
      - node_modules:/var/www/node_modules
    command: sh -lc "php artisan serve --host=0.0.0.0 --port=8000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - laravel_srm-gestao

  db:
    image: mysql:8.0
    container_name: laravel-db-srm-gestao
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: srm-gestao
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-proot" ]
      interval: 5s
      timeout: 5s
      retries: 20
    networks:
      - laravel_srm-gestao

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: laravel-phpmyadmin-srm-gestao
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8081:80"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - laravel_srm-gestao

volumes:
  db_data:
  vendor:
  node_modules:


networks:
  laravel_srm-gestao:
    driver: bridge
