services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app-srm-gestao
    container_name: laravel-app-srm-gestao
    environment:
      APP_ENV: production
      APP_DEBUG: "false"
      APP_URL: http://localhost
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: srm-gestao
      DB_USERNAME: root
      DB_PASSWORD: root
    volumes:
      - app_code:/var/www
      - app_storage:/var/www/storage
    depends_on:
      db:
        condition: service_healthy
    networks: [ laravel_srm-gestao ]

  nginx:
    image: nginx:alpine
    container_name: laravel-nginx-srm-gestao
    ports:
      - "8000:80"
    volumes:
      - app_code:/var/www:ro
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - app
    networks: [ laravel_srm-gestao ]

  db:
    image: mysql:8.0
    container_name: laravel-db-srm-gestao
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: srm-gestao
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-proot" ]
      interval: 5s
      timeout: 5s
      retries: 20
    networks: [ laravel_srm-gestao ]

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: laravel-phpmyadmin-srm-gestao
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8081:80"
    depends_on:
      db:
        condition: service_healthy
    networks: [ laravel_srm-gestao ]

volumes:
  db_data:
  app_code:
  app_storage:

networks:
  laravel_srm-gestao:
    driver: bridge
